/**
 * End-to-end pipeline test:
 *  1. list_topics — vault scan works
 *  2. research_topic — Nia web search returns papers, Tensorlake state changes
 *  3. add_note_to_vault — file actually appears in vault
 *  4. cross_reference — finds related notes
 *
 * Run: npx tsx --env-file=.env.local scripts/e2e-test.ts
 */
import {
  listTopics,
  researchTopic,
  addNoteToVault,
  crossReference,
} from "../src/lib/compound-tools";
import { Sandbox } from "tensorlake";
import { sandboxName } from "../src/lib/tensorlake";

async function dump(label: string, obj: unknown) {
  console.log(`\n── ${label}`);
  console.log(typeof obj === "string" ? obj : JSON.stringify(obj, null, 2));
}

async function main() {
  console.log("════════ COMPOUND E2E PIPELINE TEST ════════\n");

  // 1. list_topics
  console.log("[1/4] list_topics");
  const topics = await listTopics();
  console.log(`✓ ${topics.folders.length} folders, top hot link: ${topics.hotLinks[0]?.name}`);

  // 2. research_topic — get pre-state, run, get post-state
  console.log("\n[2/4] research_topic('pinescript') — testing Nia web search + Tensorlake");
  const topic = "pinescript-e2e-" + Date.now();

  // Pre-state from Tensorlake
  const all1 = await Sandbox.list();
  const sandboxBefore = all1.find((s) => s.name === sandboxName(topic));
  console.log(`Sandbox before: ${sandboxBefore ? "EXISTS" : "NONE (will be created)"}`);

  const research = await researchTopic(topic, 3);
  console.log(`✓ Tensorlake runCount=${research.state.runCount}, total papers researched=${research.state.total}`);
  console.log(`✓ Nia returned ${research.newPapers.length} new papers (${research.alreadyResearched} already known)`);
  if (research.newPapers[0]) {
    console.log(`   First paper: "${research.newPapers[0].title.slice(0, 80)}..."`);
    console.log(`   Source: ${research.newPapers[0].source}`);
  } else {
    console.log("   ⚠️ No papers — Nia web search may have returned empty");
  }

  // Post-state
  const all2 = await Sandbox.list();
  const sandboxAfter = all2.find((s) => s.name === sandboxName(topic));
  console.log(`Sandbox after: ${sandboxAfter?.status ?? "NOT FOUND"} (id=${sandboxAfter?.sandboxId ?? "—"})`);

  // 3. add_note_to_vault
  console.log("\n[3/4] add_note_to_vault — write real file to vault");
  const noteResult = await addNoteToVault(
    `_e2e-test-${Date.now()}.md`,
    `# E2E test note\n\nGenerated by pipeline test at ${new Date().toISOString()}.\n\nLinks: [[PineScript MOC]] [[Liquidity sweep detection]]\n`,
    "pinescript",
  );
  console.log(`✓ Wrote: ${noteResult.path}`);
  console.log(`   Size: ${noteResult.size} bytes`);

  // Verify file actually exists
  const fs = await import("fs/promises");
  try {
    const stat = await fs.stat(noteResult.path);
    console.log(`✓ File on disk verified (${stat.size} bytes)`);
    // cleanup
    await fs.unlink(noteResult.path);
    console.log(`✓ Cleanup done`);
  } catch (e) {
    console.log(`⚠️ File not on disk: ${e}`);
  }

  // 4. cross_reference
  console.log("\n[4/4] cross_reference — find related vault notes for 'liquidity sweep'");
  const xref = await crossReference("SMC liquidity sweep paper", "liquidity");
  console.log(`✓ Found ${xref.relatedNotes.length} related notes:`);
  xref.relatedNotes.slice(0, 3).forEach((n) => console.log(`   - ${n.relativePath}`));
  if (xref.synthesis) {
    console.log(`✓ Synthesis (${xref.synthesis.length} chars):`);
    console.log("   " + xref.synthesis.slice(0, 200) + "...");
  }

  console.log("\n════════ 🟢 E2E PIPELINE WORKING ════════");
  console.log("Tensorlake state | Nia search | Vault writes | Convex logs all verified.");
}

main().catch((err) => {
  console.error("\n✗ E2E FAIL:", err.message ?? err);
  process.exit(1);
});
